# Generated by Django 3.2.11 on 2022-02-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0011_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='file_name',
            field=models.CharField(default='Test', max_length=500),
            preserve_default=False,
        ),
    ]
